### ISSUE TITLE
CVPR 2021 paper

### ISSUE THREAD

**Issue by yuantn** [amusi/CVPR2021-Code#5]
Title: Multiple Instance Active Learning for Object Detection
Paper: https://github.com/yuantn/MIAL/raw/master/paper.pdf
Code: https://github.com/yuantn/MIAL
Category: Active Learning, Object Detection

**Comment by yuantn** [comment]
Many thanks!

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
https://github.com/amusi/CVPR2021-Papers-with-Code
